version: '3.1'

services:
  db:
    image: postgres
    hostname: dossier-db-1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: extremelysecretpasswordChangeMe!